using System.Net;
using System.Security.Claims;
using IitAcademicPortal.Application.Abstractions;

namespace IitAcademicPortal.Api.Auditing;

/// <summary>
/// Server-derived audit context for the current HTTP request. The correlation ID is generated by the server
/// for every request (never taken from a client header), and the source is the connection address, which
/// reflects the real client only when trusted forwarded headers are configured.
/// </summary>
public sealed class AuditRequestContext(IHttpContextAccessor accessor) : IAuditRequestContext
{
    public string? ActorUserId
    {
        get
        {
            var user = accessor.HttpContext?.User;
            return user?.Identity?.IsAuthenticated == true ? user.FindFirstValue(ClaimTypes.NameIdentifier) : null;
        }
    }

    public string? CorrelationId => accessor.HttpContext?.TraceIdentifier;

    public string? Source
    {
        get
        {
            var address = accessor.HttpContext?.Connection.RemoteIpAddress;
            if (address is null)
            {
                return null;
            }

            return (address.IsIPv4MappedToIPv6 ? address.MapToIPv4() : address).ToString();
        }
    }
}
