namespace IitAcademicPortal.Domain.Auditing;

/// <summary>
/// An immutable record of a mandatory business action or a security action.
/// </summary>
/// <remarks>
/// Actor and entity identifiers are historical values: they carry no foreign key to live account or
/// business rows, so deactivating or deleting the source never erases or rewrites history. Nothing
/// updates or deletes an event after it is inserted.
/// </remarks>
public sealed class AuditEvent
{
    public const int MaxEventTypeLength = 100;
    public const int MaxActorUserIdLength = 450;
    public const int MaxEntityTypeLength = 100;
    public const int MaxEntityIdLength = 200;
    public const int MaxCorrelationIdLength = 100;
    public const int MaxSourceLength = 45;
    public const int MaxMetadataBytes = 4 * 1024;
    public const int MaxChangesBytes = 16 * 1024;

    private AuditEvent()
    {
    }

    public AuditEvent(
        Guid id,
        DateTime occurredAtUtc,
        AuditEventCategory category,
        string eventType,
        AuditOutcome outcome,
        string? actorUserId,
        string? entityType,
        string? entityId,
        string? correlationId,
        string? source,
        string? metadataJson,
        string? changesJson)
    {
        if (id == Guid.Empty)
        {
            throw new ArgumentException("An event identifier is required.", nameof(id));
        }

        if (occurredAtUtc.Kind != DateTimeKind.Utc)
        {
            throw new ArgumentException("Audit timestamps are UTC.", nameof(occurredAtUtc));
        }

        Id = id;
        OccurredAtUtc = occurredAtUtc;
        Category = category;
        EventType = eventType;
        Outcome = outcome;
        ActorUserId = actorUserId;
        EntityType = entityType;
        EntityId = entityId;
        CorrelationId = correlationId;
        Source = source;
        MetadataJson = metadataJson;
        ChangesJson = changesJson;
    }

    /// <summary>Stable identifier and idempotency key, generated by the server before persistence.</summary>
    public Guid Id { get; private set; }

    public DateTime OccurredAtUtc { get; private set; }

    public AuditEventCategory Category { get; private set; }

    /// <summary>Namespaced action identifier, for example <c>auth.sign-in</c>.</summary>
    public string EventType { get; private set; } = string.Empty;

    public AuditOutcome Outcome { get; private set; }

    /// <summary>Null for unauthenticated or system activity and for failed sign-ins.</summary>
    public string? ActorUserId { get; private set; }

    public string? EntityType { get; private set; }

    public string? EntityId { get; private set; }

    public string? CorrelationId { get; private set; }

    /// <summary>Client IP address derived by the server from trusted forwarded headers.</summary>
    public string? Source { get; private set; }

    /// <summary>JSON object of safe action context approved for this event type.</summary>
    public string? MetadataJson { get; private set; }

    /// <summary>JSON array of allowlisted field changes.</summary>
    public string? ChangesJson { get; private set; }
}
